#!/bin/bash
function module_print_help() {
	cat << EOF
	Add current project to $WX_PATH

EOF
}

function module_load_options() {
    return 0
}

function module_run() {
	local dist=`getConfigPath dist dist`
	local project_name=`basename $PWD`
	main=`getConfig "main" "$project_name"`
	main_file="$dist/$main"

	test -f "$main_file" || error "File $main_file not found"
	ln -s "$main_file" "$WX_PATH/$main"
}
