#!/usr/bin/env bash

function modulePrintHelp() {
    cat << EOF
        Navigate to a projects directory
EOF
}

function autocomplete() {
    getProjects
}

function moduleRun() {
    bash --rcfile <(echo ". ~/.bashrc && cd \"${PROJECTS_DIR}/${1:-}\"")
}
