#!/bin/bash
function modulePrintHelp() {
    cat << EOF
        Navigate to a projects directory
EOF
}

function autocomplete() {
    ls "$PROJECTS_DIR"
}

function moduleRun() {
    bash --rcfile <(echo ". ~/.bashrc && cd \"${PROJECTS_DIR}/${1:-}\"")
}
