#!/bin/bash
function module_print_help() {
	cat << EOF
	Install a project with a $CONFIG file present

EOF
}

function module_load_options() {
    return 0
}

function module_run() {
	if [ -f "package.json" ]; then
		source "__ROOT__/utils/installers/node"
	elif [ -f "$CONFIG" ]; then
		source "__ROOT__/utils/installers/bash"
	else
		error "No installer found for current directory"
	fi
	
	install
}
