#!/usr/bin/env bash

function modulePrintHelp() {
    cat << EOF
        Prints the projects directory
EOF
}

function autocomplete() {
    return
}

function moduleRun() {
    echo "$PROJECTS_DIR"
}
