#!/bin/bash
function module_print_help() {
	cat << EOF
	Setup bashrc configuration

EOF
}

function module_load_options() {
    return 0
}

function module_run() {
	setupPath
    setUpBashrc
}

function setupPath() {
	safeMkdir "$HOME/.bash_completion.d"
	safeMkdir "$WX_PATH"

	if [ ! -f "$WX_PATH/wx" ]; then
		ln -s "__ROOT__/wx" "$WX_PATH/wx"
	fi
}


function setUpBashrc() {
	local content=`cat __ROOT__/../.bashrc_template __ROOT__/resources/bashrc_paths`

	# TODO Include bash_completion
	for dir in "$PROJECTS_DIR/"*; do
		if [ -d "$dir" ] && [ "$dir" != "$PWD" ]; then
			if [ -f "$dir/.bashrc" ]; then
				tmpContent=`cat "$dir/.bashrc"`
				content="${content}${tmpContent}"
			fi
		fi
	done

	echo "$content" > "$HOME/.bashrc"
}
