#!/bin/bash
function modulePrintHelp() {
	cat << EOF
	Setup bashrc configuration

EOF
}

function moduleLoadOptions() {
    return 0
}

function moduleRun() {
	setupPath
    setupBashrc
	setupBashCompletion
}

function setupPath() {
	safeMkdir "$HOME/.bash_completion.d"
	safeMkdir "$WX_PATH"

	if [ ! -f "$WX_PATH/wx" ]; then
		ln -s "__ROOT__/wx" "$WX_PATH/wx"
	fi
}


function setupBashrc() {
	local content=`cat __ROOT__/../.bashrc_template __ROOT__/resources/bashrc_paths`

	# TODO Include bash_completion
	for dir in "$PROJECTS_DIR/"*; do
		if [ -d "$dir" ] && [ "$dir" != "$PWD" ]; then
			if [ -f "$dir/.bashrc" ]; then
				tmpContent=`cat "$dir/.bashrc"`
				content="${content}${tmpContent}"
			fi
		fi
	done

	echo "$content" > "$HOME/.bashrc"
}

function setupBashCompletion() {
	if [ ! -f "$HOME/.bash_completion.d/wx-pm" ]; then
    	completion_file="__ROOT__/resources/bash_completion"
    	ln -s "$completion_file" "$HOME/.bash_completion.d/wx-pm"
    	chmod +x "$completion_file"
	fi
}
