#!/usr/bin/env bash
function exportDocument() {
    while IFS="" read -r line; do
        if [[ "$line" =~ ^source.*$ ]]; then   # Is input{...}
            path=$(echo "$line" | sed 's/source "\(.*\)"/\1/g')
            eval path="$path"

            cat "$path" | replaceProperties | exportDocument
        else
            echo "$line"
        fi
    done
}

function replaceProperties() {
    "__ROOT__/utils/applyProperties" "$CONFIG_FILE"
}

SRC="$1"
DST="$2"
CONFIG_FILE="$3"

cat "$SRC" | replaceProperties > $DST
# cat "$SRC" | replaceProperties | exportDocument > $DST
chmod +x "$DST"
