#!/bin/bash

function declareConstants() {
    $1 PROJECTS_DIR "__PROJECTS_DIR__"
    $1 WX_PATH "__PATH__"
    $1 CONFIG ".wxrc"
}

function getConfig() {
    if [ ! -f "$CONFIG" ]; then
        apply $1 "${3:-null}"
    else
        local result=`cat "$CONFIG" | jq -r ".$2"`
        if [ "$result" == "null" ]; then
            apply $1 "${3:-null}"
        else
            apply $1 "$result"
        fi
    fi
}

function hasConfig() {
    local _value
    getConfig _value "$1" null
    [ "$_value" != "null" ]
}

function getConfigPath() {
    local _path
    getConfig _path "$2" "$3"
    apply $1 "$PWD/$_path"
}

function printHelp() {
    cat << EOF

    Install and setup projects
EOF
    for module in "__ROOT__/modules/"*; do
        local moduleName=$(basename "$module")

        echo
        echo "    ${PROGNAME} `green $moduleName`"

        source "$module"
        modulePrintHelp
    done
}

function loadOptions() {
    unusedBehaviour="IGNORE"
    getOpt "--autocomplete" autocomplete
}

function autocomplete() {
    if [ $# -gt 1 ]; then
        # Targets a module's autocomplete
        local module="__ROOT__/modules/$2"
        source "$module"
        if type autocomplete &>/dev/null; then
            shift
            shift
            autocomplete "$@"
        fi
    else
        ls "__ROOT__/modules"
    fi
}


function run () {
    if $autocomplete; then
        autocomplete "$@"
        return 0
    fi

    hasMoreArgs $#

    local module="__ROOT__/modules/$1"

    if [ ! -f "$module" ]; then
        stop "Unknown mode: $1"
    fi


    source "$module"
    shift
    ARGUMENTS=("$@")
    if type moduleLoadOptions &>/dev/null; then
        moduleLoadOptions
    fi

    if [ $unusedBehaviour != "IGNORE" ]; then
        checkUnused
    fi

    moduleRun "${ARGUMENTS[@]:+${ARGUMENTS[@]}}"
}

source "__STARTER__@v2"
